simulation_config:
  map_filename: "data_maps/scenario1_map.npy"
  map_resolution_cm: 1
  initial_drone_position:
    x_cm: 3
    y_cm: 3
    height_cm: 8
  initial_angle_deg: 0
  map_axes_offset:
    x_offset: 0
    y_offset: 0
    height_offset: 0
