mission_config:
  max_steps: 100000
  boundaries:
    x_boundary:
      min_cm: 0
      max_cm: 29
    y_boundary:
      min_cm: 0
      max_cm: 30
    height_boundary:
      min_cm: 0
      max_cm: 31
  gps_resolution_cm: 1
  output_mapping_resolution_factor: 1
